spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.codec.max-in-memory-size=10MB
ollama.url=http://localhost:11434
ollama.embedding.model=nomic-embed-text
ollama.llm.model=llama3.2
embedding.provider=huggingface
embedding.dimensions=384
llm.provider=openrouter
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.model=meta-llama/llama-3.2-3b-instruct:free
huggingface.api.key=${HUGGINGFACE_API_KEY}
huggingface.model=sentence-transformers/all-MiniLM-L6-v2
jwt.secret=${JWT_SECRET}