spring.application.name=proximahire
spring.datasource.url=jdbc:postgresql://localhost:5432/proximahire
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.liquibase.default-schema=public
spring.codec.max-in-memory-size=10MB
ollama.url=http://localhost:11434
ollama.embedding.model=nomic-embed-text
ollama.llm.model=llama3.2

jwt.secret=proximahire-super-secret-key-2026-ashish-babu